@ECHO OFF
REM Top level Menu
title Work Selection Screen
color 0A
cls
ECHO **           Welcome to Work Flow Selection               **
ECHO ************************************************************
ECHO **                                                        **
ECHO **    This program is a menu system to decide where       **
ECHO **    to begin working in a new folder or an existing one **
ECHO **          Created by Me (Joe Williams) for me           **
ECHO **          Last Modified 01/17/2014                      **
ECHO[
ECHO[
ECHO[ 